### ISSUE TITLE
Set up initial django project.

### ISSUE THREAD

**Issue by RishabhJain2018** [ncs-jss/Q_hub#5]
@prakharchoudhary What is the progress on this issue ? Is it so tough ?

**Comment by prakharchoudhary** [comment]
Sir,
I m sorry, I am out of the city on vacation and didnt take my laptop along
with me. Dhruv has already told me about issue and I will push the initial
django project as soon as I come back on 13. I apologise for the delay, as
I had no knowledge of this vacation beforehand and came to know about it
only when i reached home, else I would have set up the django project
before the winter break itself.

Prakhar Choudhary

**Comment by RishabhJain2018** [comment]
@prakharchoudhary its okk . :-)

**Comment by prakharchoudhary** [comment]
@RishabhJain2018 sir I have just made a PR with the initial backend ready. It has the login signup functionality and the question upload edit and delete. The things to be added (as much I remember) are also mentioned in the PR. Will be working on them soon. Please review and suggest any changes.
