### ISSUE TITLE
Make frontend folder systematic.

### ISSUE THREAD

**Issue by RishabhJain2018** [ncs-jss/Q_hub#6]
The files in the folder must be in order like `css` files must be under `frontend/css/filename` with proper naming conventions.

**Comment by nikitiwari** [comment]
sir,
Issue resolved.
I have done as you said.Please check and tell if there is any other error.

**Comment by RishabhJain2018** [comment]
@nikitiwari Please create a PR from your branch on the master branch.

**Comment by nikitiwari** [comment]
sir ..i have created the PR from my branch on the master branch
